### ISSUE TITLE
Code is not compatible with python 3

### ISSUE THREAD

**Issue by SamMugel** [charleswhchan/dwave-ocean-qubo-examples#1]
I have edited your code to make it compatible with python 3.

If you give me the right to push I will send you a pull request

**Comment by charleswhchan** [comment]
Thanks @SamMugel! Much appreciated. 

Please go ahead and create a fork of the repo then create a PR -- I will review and approve after. Here's a short tip on how to change clone to a fork https://gist.github.com/jagregory/710671 
(Is this what you are asking?)

**Comment by SamMugel** [comment]
understood

**Comment by charleswhchan** [comment]
Fixed by PR #2
